### ISSUE TITLE
Facets output incompatible with Facets Preview

### ISSUE THREAD

**Issue by anoronh4** [mskcc/tempo#988]
https://github.com/mskcc/tempo/blob/2ea61ff7e0012112426df3d35a03ca4879024e14/modules/process/Facets/DoFacetsPreviewQC.nf#L24

the `DoFacetsPreviewQC` module copies the `facets_qc.txt` and only publishes the copy. This file is not recognized by Facets Preview

Also `facets_manifest.txt` should ideally be generated for ease of use with facets preview, although i'm not sure how to generate that.

**Comment by price0416** [comment]
Addressed this issue in facets preview.  Facets preview will now accept any file that contains facets_qc.txt as part of its file name.
